version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - docker build -t app:base .
      - docker build -t app:dev . -f Dockerfile-dev
      - docker build -t app:test . -f Dockerfile-test
      - docker run --detach --name=db --env="MYSQL_ROOT_PASSWORD=password" mysql:5.7
  build:
    commands:
      - docker run --link db:mysql app:test ./bin/rake db:create
      - docker run --link db:mysql app:test ./bin/rake db:test:prepare
      - docker run --link db:mysql app:test ./bin/rspec
  post_build:
    commands:
      - docker stop db
      - docker rm db
