FROM app:dev

COPY . $APP_ROOT
RUN $APP_ROOT/bin/yarn
RUN $APP_ROOT/bin/webpack
RUN $APP_ROOT/bin/rails assets:precompile
RUN $APP_ROOT/bin/rails db:environment:set RAILS_ENV=test
RUN RAILS_ENV=test $APP_ROOT/bin/rake db:test:prepare
RUN $APP_ROOT/bin/rspec
RUN $APP_ROOT/bin/rails test
RUN npm test
RUN bundle exec yard
