development:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  tag:           'app.development'
  messages_type: 'string'
staging:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  tag:           'app.staging'
  messages_type: 'string'

production:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  tag:           'app.production'
  messages_type: 'string'