@startuml
salt
{+
  {
   [検索] | [JSONで保存] | [CSVで保存]
  }

  {#
  タイトル | 著者    | 言語    | 出版年 | 売上部数
  String  | String | String  | date  | Decimal
  String  | String | String  | date  | Decimal
  String  | String | String  | date  | Decimal
  String  | String | String  | date  | Decimal
  }
}
@enduml