@startuml
left to right direction
skinparam packageStyle rectangle
actor User
rectangle Whinepad {
  User -- (ワインリストを新規作成する)
  User -- (ワインリストの詳細を表示する)
  User -- (ワインリストを編集する)
  User -- (ワインリストを削除する)
  User -- (ワインリストを検索する)
}
@enduml