#!/bin/bash
cd /home/ec2-user/ruby-on-rails
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
source ~/.nvm/nvm.sh
nvm install 7.4.0
yum install postgresql-devel -y
wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
yum install yarn -y
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm requirements
rvm install 2.4.0
gem install rails
bundle install
chmod 755 bin/webpack
bin/yarn
bin/webpack
bin/rails assets:precompile
bundle exec passenger start -p 80 -a 0.0.0.0 -d
